language: scala
scala: 2.12.6
jdk: oraclejdk8

stages:
- name: test
- name: publish
  if: NOT type = pull_request

services:
  - docker

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
    - "$HOME/.coursier/cache"
    - ".hoarder-cache"

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "kbsEoBDy82f1R4XW0ygLetNM2r1sx2MAvCzOG5qsAqt2RwMuW6o1SMqnoZkDFyk+kRa4txKRUkAANOl2dCMQd4Yx/jVPkZHTJTnfeyv0rZYFMNPKBs86D8KgaGR3z+7HTJ83ofgoRcMVtmGq1S1aW1so+if/BpGFfoyQgm4kWyz6IGYqDGMFQS4v8bUM1fX7Xc8vknNOuQAaD4jaCW6eaauuO3gfjidQtSazd5LcZqP8/YytoJ6PszdmXo777CWsHKRm7bMmKbROdLcNaCah31Xni0wfeWsGrJttAL78RBqy7lb32BOG+8szCNBjCL6Ghn4SV2x6ftQsbBEiJuLg2BnpTNZu3CJG8kziI4V+pWvKgPgiUopQ0XeDa3SFRG/lxmm0KpyUuRqoMlTkco8dcvmm8eznegF5oFRJXkI0YB/2Wm1x+3vxbNWGwjOgW8fORGoYGllu//2hyxKGLjmBGOYmXLQ/WhpNY0TYio84wsWA8lMhCgQUhKJ+0ODNtsv+qclzrCadJ0+ACCa36w22Xp93yYJScQZyj8vw/jD7fTMgZHOt5d/xxijSyLlV3qbhBEpDuqxtVep0D3avcZqR0A5xncFbMesNn6f7KGLbKWwuGfm67/Zs+RVLRh6FyeabgrJtbU6+OdiUUOoGE3zNlebKmTpYyo2KwgY6qN5dRFQ="
    # GITHUB_TOKEN
    - secure: "XBPObdqHjI9kzA8fDj92HXx5PInVDocZvOo1LG+5YjRmdoyvpa4tO84e8aiunMjL1/J3GxIsG2mjgxrJpu+31ntft58YfJvJxvLE+FI4wm27FIyrnHAkqyDuCxWa70icaCeZGc6jhLEEpc0mOgrmcgM0/L1tLdoXIr8F6DfyOWoI4ItIAg79oZ/fayXgPgFFbbHJXOtR6DRgGOUU+3TimZleM/DzbznOnmNfnxSVICPnx/pLaJe3HWsPjkL739u0SBRh02ANa1V4Cy4rYXq5criTsLMc8Rk5xstoULzm+0ajuZCRf97FJUQgW/qe5qxTdGwgEBySOWp78ejImdzp9XxssozGXaqt9dSc6pa11aJb7QCv66w+V/eWl2yrWtIVzfsAqn+NYUcA7/JDt5d1K1A11XzcdzqYwrVwEutsRfMn+o9mCwEPcbmLHWHQ20tZNtKh83UnceGiQIdA/SM+LEyzMPoYRSXvt4+xm3gUC8BHPnIoK+zjV9gBiyxh0qP1Jrm/qPmq7g0dHyG3AH6PSbY5LPI/fkIeiiwlcdOa479SUzrfecDkHByoBpC+3D8FiwUGk4bDQpAkZrxF1lwsYcg53ylhVuLOQq9VAFYob2Vj2Hk5W9LxX9xF2+/cYswRTMPRJPMk0mQ1QTAXQebU/72fJgLVmHYyTEIAGiIDERg="
    # GITHUB_ACCESS_TOKEN
    - secure: "VEfYD4y+l5u/bFZfvUZKDiT523VvWhMXGIQkfxTSCdm+j1FxJVINtOhpNCj8+th/XCspNAklHH+1Ax2WlUdHpZ73T5w7FQpVkVICAhKcP17iHOl1pLugZJ/i8wI4OiTc84CUX0DVopY4KFerF6hyyOD+h4QRJ8QglnWEXqMNe1n4Wi0rDFdeyg+tWWJWp0dTiSN3zjBny6nc5pFO7T7gRoUaGUB2UqV0XQDPZzKh2/ss20zLQBwUFQLoXbKXkSCyK+QMMsFnh8eHb38vudZhoaYMbnPRAnG+Z4tNzBW9mNMV0DWW0iNOz4kGdXbKPIAzxHCiBuPjbrEVhl1MCX9w1OIaGi1k399Uktv7nu9H6MBMmtKbXxJZsJuEYogWbgqu7vkRyZ2cibh2s7nUvXMKr+8r+sV9ZDiEmPtL1uTjl9MK1aKeShUJGNdP0bWPgMgm+Cx4BeRTADn6oC6CRu9FzLyps/CiOeWbeygpDoevgj1ijIKZ/LscMv8ZmWJIwrTDu58olYVOBZodeJyxEbdyb8T9D4qHgs1p4Isk8j/jTHczQ4034tkLPPf9IoskicPZalL1YfbpdkZkM8qLOh0ZQZRiJIFrGISYczmp5AoF3IAJoqCxiKWqklbAD/y2dc7t+nYY+gRNSGFjqf/+z0Y+QKvu7rGqOZlqokkz9ZxheII="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "RubzCbQ1mU7t8NEPNzt4eag9HoKrc5BPBwzXGg0wz9M4rAu7/ZAoqp/7JPB/IocO5xop+VMuyxmMiJQ8YA2wPxuWQSpnBY9GClNO3yNzSUiz72NgwIcBZcLkQ1dcScpP+OHqKvl9Y88MeIHHcSJAqFOBPpHDrXgPDfa3X80VkW3B3K+yBGhzWeez7l6aLMJXIzCDTBTF+q7+fiQaAc1gDW6RgWYybyhRoSUdbrh2anbkS/vCZ5pDHZaAZagh1Pn4UOxFcx7hatnhuo6Q81CvM+WWL2LQelqj+75Y9RPugXPZGUsjXLCXFkO5O3ND4eJo67mvVPr8xUABKt3++VQAHF9u05QYLybMhYJJCs+ggkLaKUwAtCHB63wtPcQ/ZQE5X5fUw/JixakRNmqnPWMgxPasjG59LoRtDIWwo8IM0F6S2zYzio7SiYVSudhGj8eeqvQJ5pVF1W5D9XnytvjbjOT+dzh1Y6QQc7dxaYMMU80jCAbnpVuyahJers5AyHoUEjTnP4pbETn2O0AY9hw2eCZtFA0i9JSDHeH4JNcdjLzIOMxUU6wFeDh0es90phxOOCH3wpQxsRDoUs/J3P1A1LSSL9hsYr4bnQTqus61xvJ2RWCLlfYbaS99qsWuypS7Sq/yn2s9naKw4hAvRc3R9xW006PqUAUnGZ1d7wmpbGc="

install:
  - gem install octokit

  - git config --global user.email "bot@slamdata.com"
  - git config --global user.name "SlamData Bot"

jobs:
  include:
  - stage: test
    script:
      - docker run -d -p 127.0.0.1:27018:27017 --name mongodb bitnami/mongodb:4.1.4
      - set -e
      - "$SBT ++$TRAVIS_SCALA_VERSION test"
  - stage: publish
    script:
      - set -e
      - "$SBT transferPublishAndTagResources"
      - TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-datasource-mongo'
    git:
      depth: false

after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST != "false" ] && [[ $TRAVIS_PULL_REQUEST_BRANCH =~ 'version-bump' ]]; then
      clone_dir=$(mktemp -d "/tmp/slamdata-bump.XXXXXXXX")
      git clone --depth 1 https://$GITHUB_TOKEN@github.com/slamdata/devtools.git $clone_dir

      for t in "$(scripts/listLabels | grep 'version: revision')"; do
        $clone_dir/bin/sdmerge $TRAVIS_REPO_SLUG $TRAVIS_PULL_REQUEST
      done
    fi

  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
  - master
  - "/^backport.*$/"

before_cache:
- find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
- find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
