language: scala
scala: 2.12.6
jdk: oraclejdk8

stages:
- name: test
- name: publish
  if: NOT type = pull_request

services:
  - docker

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
    - "$HOME/.coursier/cache"
    - ".hoarder-cache"

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "C05VIZXI/Q7vQP5OZyIysriUFHdhldbToeGdue+Gcg7TxT0xOJjacYLW/CLhn9kXE6h+FusvrANU3ZkGs5Y/QNItP1NJCwybhJRAxFkCjoWO2MVhr2nERWJcTmEpVYqV8gfIC5En//T4o30uGNdBBy6ZrNoOdiCWZ5Jo5PxfB/1p7pFhwrBrlA8x06gL3cq5E+GqIRcMhQzjrijF0KIvxpJ2G7wC/CjUu13fErK2B7uXLGyivP2VCb6M95dTIU/ajB2xpXO/pdfmPFGc8R48qgAK1qEd9S8za8KSBrRFeVE5/7NFo/6d9DGRTDWLIyNOSlhw5FTf2KD3r3NmHVXdVea/s7KkHfcqnYOzSC69rKR+QXCR8uWMMz+p6by4o3IcpyQSiZNbxO6awq0P/Pn7l7ntZ6p6Ejc/eXO79JdE8X4LMJxHXbp3FMEzH5te4OHvi1qfHGJ5ydbUcDpBh+5QarMKyZjXcfhCz+zuNCU/nHExlnm8XwIw/gntBU1AptCmAyftuOIY54nCHKXxzzRX1xC80zFYsDpOMzcGc/szJk51RDIh3U1lkS7i4nTK7O9HjTm4xITAwNwkAL75YKQ8NaFEd61zymPZn0lSMXrQNClAluVM8R61qfauL3XVNFCgYhsQDWjONCn3rpCBUh09F8REQPRw4Yi+8pIAh3u0/QE="
    # GITHUB_TOKEN
    - secure: "OBNwoqh6xaxxY6O3NzX9eWjnHlL9G9UvK4bKrwqM2UcxYSjVopg1gGNS3tKCbc5qbjeTsLdK+BkWpyJIsVT4QP+jOKFTyjADcwT0I82y5AwWfSnm3i06/JWZVS5Kvxtcae0nJVSMaaXXM/YBIFXbZumu4Uj5RYpU2bp4mhdpjTixBGH4QofURtt3DRsvAF15CTONCTBHAQi/FBDCEbV4n9hxmDGHe3S5yKnNRmHWMzXgSZ1b871anzesWTLXVm6g1p122LZR3i/InNu8cxz66X3BAMxyr5rdEU0niLcDIHNM+CFPn4aYna8RpvIg123lmKrnwX/7r//kDwlmbT4L89/1ysLu3fwlvLJdQXQwFq8vvCJxM+OE5ix+q8c/McE5qFr4pxh0XunYVH28EK9YWroVTHihdgCbKSUsRR+B/uSzfKLj9Mk49zju2OHByC3w3c0KZJdbDd/T2JiQsGwWB1C9W788xYp548u/STd3PU1w13yaXK0eu5zkQUhxImOQJeIFDu3a+vXH+NuOmM0zUSBhwNa9jLhOVTs1tINR3SnoaUa2Hpuq5TSRbwjW1GLL6R7fYA66zZjAkOqKOH8bTjMA8dXqB9K6QzSt5ag6RzMtz2JasIBRNLU3Jn0i395tWFTRMfsh8p+SBm7BiyMAgzdNnAva7HZgiPpA5UoH1ps="
    # GITHUB_ACCESS_TOKEN
    - secure: "QtxsiT+GU7tnl8kHlWRwnTH5uJ7P+2T6yRSrwVsfuyogmARoHUUe0FgvOwmCr+0IYAnsmyXlXBZj7SwALUyc31DffOZrPCLHGZPJ51ZfDJ0nE66QtQ0su3GG4fZ6KG5mRtj0soMGvGxL011VhAX2ikAU6cTR/5AsUTH5AQPJjFuo/1w7nHaAuDYceDzvZqJXFDSu8d3nIHLi8MM61PM3dDpN1/jHYnOLZ80tsFdzgwZtGTFaqePQpZe5pBj4V07MrMSqvwm5ORKkg21jTMKMpLS9rM+kzMH36HcMwaNKN2Z+S+ujWFw3Aie+viZ/KxBXCPTZSeIcreG05IDvh9djbUWUQ5rUqxYxnebWw14/N9UyXskE10u/8FJN0wLYuRr1d+MMsy6Ti6GskOWZaHYVb34Tx91KrEHiImxMeC8znxJfam2SDi14oSxYUyDq8D7UFflVX7uL/oK9jem8P63gQ/L+o5zwceqx+aS9B1GUu8mpEjGkDVhLeYrLOv1gJ8XcPzuCQMnUKlpsO01aALbNHLPM0wIuk3tn5p1YVerNuA9Jest1HJuTZy1jcRY5L4GqGhEuQ4csaxhRsHxJsKhS2kss3zclanV92JwitkInU2BEhWO9k2XfPm4Re4Kgqq9xxtWaaQCa46qIsHnMX0mMbu0bL80pKz9MeGMRS2Ulgqc="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "aqyKVkaXByqBsCia1hDxlp59MmUGESKi4CtDNKxVcE6PCdDiMhVR71H2udWIUhPB/xNLqs7JBOmmrZYlmGM/ea8OVBrB5Lj2gSmNcO5Uthb98FnjnQCG/nRJWxjBdA0QhYGH3f9WARdezVvB/diZRTiusEC8qyWUkP3UPb1idDYzTwRVxBpq5/4A5wZ4ablRuIYmBOscZVFQGQ7y2vtkNCETkTIYtr1jjA26u+kUe3IgjgjhZFSz8pnw7RaEQUjuL/UEpZGlasT45EcYJuneGuxI36EqvCgqrm7vORpnxIsKk6KqPdpFH7ePWEgt1yFUVDipecKx5M/PvKXaeBofkhSgT6gA4ygOPsK9wqQtzNms4pqzski9S6A4ioj3odCfDiA82rAA0VRQMu7Kn8RFV5wiNU+K12UeV/GYz/zNIFk+fR/5II/okBheInj1vs1opUDjgHPaFZIUTABzqaurQ1O/IK31TRc5R4IswnqChllHxD289+A8lPiWM6RUDeS+G0TI85VQtdywUrtPnvkyLO3OTwTXLENPFSF5I21GgEZUStX+p0G+7XJ/QxQ28kIV1vf0XSjVyTmmi55tt/l5m6V6ksyce6M0ttjnLsJ7g/EjRG3EA0U+bq5MXI38RRh/vLEF8Ku+Xk6NBuI+5OhrD8X91cO/UcHsC+sALIZ+o5A="

install:
  - gem install octokit

  - git config --global user.email "bot@slamdata.com"
  - git config --global user.name "SlamData Bot"

jobs:
  include:
  - stage: test
    script:
      - docker run -d -p 127.0.0.1:27018:27017 --name mongodb bitnami/mongodb:4.1.4
      - set -e
      - "$SBT ++$TRAVIS_SCALA_VERSION test"
  - stage: publish
    script:
      - set -e
      - "$SBT transferPublishAndTagResources"
      - TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-datasource-mongo'
    git:
      depth: false

after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST != "false" ] && [[ $TRAVIS_PULL_REQUEST_BRANCH =~ 'version-bump' ]]; then
      clone_dir=$(mktemp -d "/tmp/slamdata-bump.XXXXXXXX")
      git clone --depth 1 https://$GITHUB_TOKEN@github.com/slamdata/devtools.git $clone_dir

      for t in "$(scripts/listLabels | grep 'version: revision')"; do
        $clone_dir/bin/sdmerge $TRAVIS_REPO_SLUG $TRAVIS_PULL_REQUEST
      done
    fi

  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
  - master
  - "/^backport.*$/"

before_cache:
- find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
- find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
